#!/usr/bin/env python

import sys
sys.path.append("/aquarium-ctrl/aquarium_controller/")

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "aquarium_controller.settings")

import django
django.setup()

import backend.control
backend.control.loop()
